/**
 * @file pgvector.int.spec.ts — integration tests for the pgvector stack
 * (Phase 4). Exercises `EmbeddingIndexerService` and the semantic-tools
 * SQL against a real PostgreSQL 16 + pgvector instance.
 *
 *  Gating: this suite SKIPS unless `INTEGRATION_DB_URL` is set. To run:
 *    INTEGRATION_DB_URL=postgresql://neoleadge:pass@localhost:5432/neoleadge \
 *      npx jest src/ai/embeddings/pgvector.int
 *
 *  The target DB must have the `vector` extension available
 *  (pgvector/pgvector:pg16 has it preinstalled — `CREATE EXTENSION` is
 *  fine to run inside the test).
 *
 *  Isolation: each test run creates a unique schema (`int_<ts>_<rand>`),
 *  installs minimal copies of the tables the indexer writes to, runs its
 *  assertions, then drops the schema. Safe to run against a shared DB
 *  even with other suites going in parallel.
 *
 *  Embeddings are NOT generated by the real e5 model. We stub
 *  `EmbeddingsService.embed` to return deterministic 4-dim unit vectors
 *  keyed by input text — keeps the cosine-similarity assertions exact.
 *  (The retrieval eval at `scripts/eval-retrieval.mjs` exercises the
 *  real e5 model end-to-end against the live test server; this suite
 *  exists to catch SQL-shape regressions in the indexer + tools.)
 */

import { Client } from 'pg'
import { Logger } from '@nestjs/common'
import { EmbeddingIndexerService } from './embedding-indexer.service.js'
import type { EmbeddingsService } from './embeddings.service.js'

// ─── Gating ──────────────────────────────────────────────────────────────────

const DB_URL = process.env.INTEGRATION_DB_URL ?? ''
const describeInt = DB_URL ? describe : describe.skip
const TEST_DIM = 4 // small enough to write by hand; cosine math works at any dim

if (!DB_URL) {
  // eslint-disable-next-line no-console
  console.warn('[pgvector.int.spec] INTEGRATION_DB_URL not set — suite is SKIPPED.')
}

// ─── Test fixtures ───────────────────────────────────────────────────────────

/** Deterministic 4-dim unit vector keyed by a label. Tests pick labels so
 *  they can predict which row wins cosine similarity:
 *
 *    VEC_A = [1, 0, 0, 0]   "PostgreSQL"-like
 *    VEC_B = [0, 1, 0, 0]   "DocuSign"-like
 *    VEC_C = [0, 0, 1, 0]   "Kubernetes"-like
 *    VEC_AB = [0.7, 0.7, 0, 0]  near A, also near B
 */
const VEC: Record<string, number[]> = {
  A:  [1, 0, 0, 0],
  B:  [0, 1, 0, 0],
  C:  [0, 0, 1, 0],
  AB: [0.7071, 0.7071, 0, 0],
}

function makeStubEmbeddings(): EmbeddingsService {
  // The indexer calls .isConfigured() then .embed(texts, inputType, opts).
  // We return one VEC entry per text — caller must pass texts whose first
  // char picks the vector (e.g. "A-segment-1", "B-field").
  const stub = {
    isConfigured: () => true,
    embed: jest.fn(async (texts: string[]) => {
      const vectors = texts.map((t) => {
        const key = t.charAt(0).toUpperCase()
        const v = VEC[key]
        if (!v) throw new Error(`stub embed: no vector for prefix "${key}"`)
        return v
      })
      return { isSuccess: true, isFailure: false, value: vectors, error: undefined }
    }),
  }
  return stub as unknown as EmbeddingsService
}

/** Minimal Prisma shim exposing only the two raw methods the indexer +
 *  semantic SQL use. Backed by a single pg.Client bound to the test schema. */
class PgShim {
  constructor(private readonly client: Client) {}

  async $executeRawUnsafe(sql: string, ...params: unknown[]): Promise<number> {
    const res = await this.client.query(sql, params)
    return res.rowCount ?? 0
  }

  async $queryRawUnsafe<T>(sql: string, ...params: unknown[]): Promise<T> {
    const res = await this.client.query(sql, params)
    return res.rows as T
  }
}

interface Schema {
  client: Client
  schemaName: string
  indexer: EmbeddingIndexerService
}

async function setupSchema(): Promise<Schema> {
  const client = new Client({ connectionString: DB_URL })
  await client.connect()

  // Confirm pgvector is installed (idempotent).
  await client.query('CREATE EXTENSION IF NOT EXISTS vector')

  const schemaName = `int_${Date.now()}_${Math.floor(Math.random() * 100_000)}`
  await client.query(`CREATE SCHEMA "${schemaName}"`)
  await client.query(`SET search_path TO "${schemaName}"`)

  // Minimal tables — only the columns the indexer SQL touches. Column names
  // and quoting MUST match production: indexer hardcodes `"TranscriptSegments"`,
  // `"ProjectFieldValues"`, `"MeetingTranscripts"`, `"summaryEmbedding"`, etc.
  await client.query(`
    CREATE TABLE "Projects" (
      id text PRIMARY KEY,
      name text
    );
    CREATE TABLE "ProjectFields" (
      id text PRIMARY KEY,
      "projectId" text REFERENCES "Projects"(id),
      label text,
      "fieldType" text DEFAULT 'Text',
      "isRequired" boolean DEFAULT false,
      "isBacklogDriver" boolean DEFAULT false,
      "backlogHint" text
    );
    CREATE TABLE "ProjectFieldValues" (
      id text PRIMARY KEY,
      "projectId" text REFERENCES "Projects"(id),
      "projectFieldId" text REFERENCES "ProjectFields"(id),
      value text,
      embedding vector(${TEST_DIM})
    );
    CREATE TABLE "MeetingTranscripts" (
      id text PRIMARY KEY,
      "projectId" text REFERENCES "Projects"(id),
      title text,
      "createdAt" timestamptz DEFAULT now(),
      "aiSummary" text,
      "summaryEmbedding" vector(${TEST_DIM})
    );
    CREATE TABLE "TranscriptSegments" (
      id text PRIMARY KEY,
      "transcriptId" text REFERENCES "MeetingTranscripts"(id),
      speaker text,
      text text,
      "startTime" int DEFAULT 0,
      "endTime" int DEFAULT 0,
      embedding vector(${TEST_DIM})
    );
  `)

  const indexer = new EmbeddingIndexerService(
    new PgShim(client) as unknown as ConstructorParameters<typeof EmbeddingIndexerService>[0],
    makeStubEmbeddings(),
  )
  // Silence the indexer logger so test output stays readable.
  Object.defineProperty(indexer, 'logger', { value: new Logger('test-indexer'), writable: true })

  return { client, schemaName, indexer }
}

async function teardown(s: Schema): Promise<void> {
  try {
    await s.client.query(`DROP SCHEMA "${s.schemaName}" CASCADE`)
  } finally {
    await s.client.end()
  }
}

async function seed(client: Client, projectId: string): Promise<void> {
  await client.query(`INSERT INTO "Projects"(id, name) VALUES ($1, $2)`, [projectId, projectId])
}

// ─── Tests ───────────────────────────────────────────────────────────────────

describeInt('pgvector integration — indexer + semantic SQL', () => {
  jest.setTimeout(60_000)

  let s: Schema

  beforeEach(async () => {
    s = await setupSchema()
  })
  afterEach(async () => {
    await teardown(s)
  })

  describe('EmbeddingIndexerService.indexAndStore', () => {
    it("writes embedding for target='segment'", async () => {
      await seed(s.client, 'p1')
      await s.client.query(`INSERT INTO "MeetingTranscripts"(id, "projectId", title) VALUES ('m1', 'p1', 'kickoff')`)
      await s.client.query(`INSERT INTO "TranscriptSegments"(id, "transcriptId", speaker, text) VALUES ('s1', 'm1', 'PM', 'about A')`)

      const result = await s.indexer.indexAndStore(
        'segment',
        [{ id: 's1', text: 'A-segment-text' }],
        { projectId: 'p1' },
      )

      expect(result).toEqual({ indexed: 1, failed: 0 })
      const { rows } = await s.client.query<{ embedding: string | null }>(
        `SELECT embedding::text FROM "TranscriptSegments" WHERE id='s1'`,
      )
      expect(rows[0].embedding).not.toBeNull()
      expect(rows[0].embedding).toContain('1,0,0,0')
    })

    it("writes embedding for target='field-value'", async () => {
      await seed(s.client, 'p1')
      await s.client.query(`INSERT INTO "ProjectFields"(id, "projectId", label) VALUES ('f1', 'p1', 'Stack')`)
      await s.client.query(`INSERT INTO "ProjectFieldValues"(id, "projectId", "projectFieldId", value) VALUES ('v1', 'p1', 'f1', 'A: postgresql')`)

      const result = await s.indexer.indexAndStore(
        'field-value',
        [{ id: 'v1', text: 'A: postgresql' }],
        { projectId: 'p1' },
      )

      expect(result).toEqual({ indexed: 1, failed: 0 })
      const { rows } = await s.client.query<{ embedding: string | null }>(
        `SELECT embedding::text FROM "ProjectFieldValues" WHERE id='v1'`,
      )
      expect(rows[0].embedding).not.toBeNull()
    })

    it("writes summaryEmbedding for target='summary'", async () => {
      await seed(s.client, 'p1')
      await s.client.query(`INSERT INTO "MeetingTranscripts"(id, "projectId", title, "aiSummary") VALUES ('m1', 'p1', 'kickoff', 'A summary')`)

      const result = await s.indexer.indexAndStore(
        'summary',
        [{ id: 'm1', text: 'A: summary text' }],
        { projectId: 'p1' },
      )

      expect(result).toEqual({ indexed: 1, failed: 0 })
      const { rows } = await s.client.query<{ summaryEmbedding: string | null }>(
        `SELECT "summaryEmbedding"::text AS "summaryEmbedding" FROM "MeetingTranscripts" WHERE id='m1'`,
      )
      expect(rows[0].summaryEmbedding).not.toBeNull()
    })

    it('returns indexed:0 when texts is empty (no SQL roundtrip)', async () => {
      const result = await s.indexer.indexAndStore('segment', [], { projectId: 'p1' })
      expect(result).toEqual({ indexed: 0, failed: 0 })
    })

    it('skips empty/whitespace-only text items upstream', async () => {
      await seed(s.client, 'p1')
      const result = await s.indexer.indexAndStore(
        'segment',
        [{ id: 's1', text: '   ' }, { id: 's2', text: '' }],
        { projectId: 'p1' },
      )
      // Filtered before the embed call; not counted as failed.
      expect(result).toEqual({ indexed: 0, failed: 0 })
    })
  })

  describe('semantic SQL — cosine similarity + multi-tenancy', () => {
    async function seedTwoSegmentsAcrossProjects(): Promise<void> {
      await seed(s.client, 'p1')
      await seed(s.client, 'p2')
      await s.client.query(`INSERT INTO "MeetingTranscripts"(id, "projectId", title) VALUES ('m1', 'p1', 'p1-meet'),('m2', 'p2', 'p2-meet')`)
      await s.client.query(`INSERT INTO "TranscriptSegments"(id, "transcriptId", speaker, text) VALUES ('s1', 'm1', 'PM', 'A-text'),('s2', 'm1', 'PM', 'B-text'),('s3', 'm2', 'PM', 'A-text')`)
      // Manually set vectors using literal cast — matches what indexAndStore writes.
      await s.client.query(`UPDATE "TranscriptSegments" SET embedding = '[1,0,0,0]'::vector WHERE id='s1'`)
      await s.client.query(`UPDATE "TranscriptSegments" SET embedding = '[0,1,0,0]'::vector WHERE id='s2'`)
      await s.client.query(`UPDATE "TranscriptSegments" SET embedding = '[1,0,0,0]'::vector WHERE id='s3'`)
    }

    it('returns the closest segment first when querying with VEC_A', async () => {
      await seedTwoSegmentsAcrossProjects()
      const { rows } = await s.client.query<{ segmentId: string; similarity: string }>(
        `SELECT s.id AS "segmentId",
                1 - (s.embedding <=> $1::vector) AS similarity
           FROM "TranscriptSegments" s
           JOIN "MeetingTranscripts" m ON m.id = s."transcriptId"
          WHERE m."projectId" = $2
            AND s.embedding IS NOT NULL
       ORDER BY s.embedding <=> $1::vector ASC
          LIMIT 5`,
        ['[1,0,0,0]', 'p1'],
      )
      expect(rows[0].segmentId).toBe('s1')
      // Cosine similarity of identical unit vectors = 1.0 (subject to float).
      expect(Number(rows[0].similarity)).toBeCloseTo(1, 5)
      expect(rows[1].segmentId).toBe('s2')
      expect(Number(rows[1].similarity)).toBeCloseTo(0, 5)
    })

    it('multi-tenancy: query scoped to projectId does NOT leak other-project hits', async () => {
      await seedTwoSegmentsAcrossProjects()
      const { rows } = await s.client.query<{ segmentId: string; projectId: string }>(
        `SELECT s.id AS "segmentId", m."projectId" AS "projectId"
           FROM "TranscriptSegments" s
           JOIN "MeetingTranscripts" m ON m.id = s."transcriptId"
          WHERE m."projectId" = $2
            AND s.embedding IS NOT NULL
       ORDER BY s.embedding <=> $1::vector ASC
          LIMIT 5`,
        ['[1,0,0,0]', 'p1'],
      )
      // p1 has 2 segments; p2 has 1 with the SAME vector as p1's s1.
      // A leak would surface s3 here. It must not.
      expect(rows.map((r) => r.segmentId).sort()).toEqual(['s1', 's2'])
      for (const r of rows) expect(r.projectId).toBe('p1')
    })

    it('respects minSimilarity floor — drops rows below the threshold', async () => {
      await seedTwoSegmentsAcrossProjects()
      const { rows } = await s.client.query<{ segmentId: string }>(
        `SELECT s.id AS "segmentId"
           FROM "TranscriptSegments" s
           JOIN "MeetingTranscripts" m ON m.id = s."transcriptId"
          WHERE m."projectId" = $2
            AND s.embedding IS NOT NULL
            AND (1 - (s.embedding <=> $1::vector)) >= $3
       ORDER BY s.embedding <=> $1::vector ASC`,
        ['[1,0,0,0]', 'p1', 0.5],
      )
      // Only s1 (similarity 1.0) survives; s2 (0.0) is below 0.5.
      expect(rows.map((r) => r.segmentId)).toEqual(['s1'])
    })

    it('skips rows where embedding IS NULL (backfill window safety)', async () => {
      await seed(s.client, 'p1')
      await s.client.query(`INSERT INTO "MeetingTranscripts"(id, "projectId", title) VALUES ('m1', 'p1', 'meet')`)
      // Two segments, only one has an embedding.
      await s.client.query(`INSERT INTO "TranscriptSegments"(id, "transcriptId", text) VALUES ('s-yes', 'm1', 'embedded'),('s-no', 'm1', 'not embedded')`)
      await s.client.query(`UPDATE "TranscriptSegments" SET embedding = '[1,0,0,0]'::vector WHERE id='s-yes'`)

      const { rows } = await s.client.query<{ segmentId: string }>(
        `SELECT s.id AS "segmentId"
           FROM "TranscriptSegments" s
           JOIN "MeetingTranscripts" m ON m.id = s."transcriptId"
          WHERE m."projectId" = $2 AND s.embedding IS NOT NULL
       ORDER BY s.embedding <=> $1::vector ASC`,
        ['[1,0,0,0]', 'p1'],
      )
      expect(rows.map((r) => r.segmentId)).toEqual(['s-yes'])
    })
  })

  describe('end-to-end: indexer writes survive a retrieval round-trip', () => {
    it('a fresh indexer call → segment is retrievable by cosine search', async () => {
      await seed(s.client, 'p1')
      await s.client.query(`INSERT INTO "MeetingTranscripts"(id, "projectId", title) VALUES ('m1', 'p1', 'meet')`)
      await s.client.query(`INSERT INTO "TranscriptSegments"(id, "transcriptId", text) VALUES ('s1', 'm1', 'Note about A')`)

      await s.indexer.indexAndStore(
        'segment',
        [{ id: 's1', text: 'A-segment-payload' }],
        { projectId: 'p1' },
      )

      const { rows } = await s.client.query<{ segmentId: string; similarity: string }>(
        `SELECT s.id AS "segmentId", 1 - (s.embedding <=> $1::vector) AS similarity
           FROM "TranscriptSegments" s
           JOIN "MeetingTranscripts" m ON m.id = s."transcriptId"
          WHERE m."projectId" = $2 AND s.embedding IS NOT NULL
       ORDER BY s.embedding <=> $1::vector ASC`,
        ['[1,0,0,0]', 'p1'],
      )
      expect(rows[0].segmentId).toBe('s1')
      expect(Number(rows[0].similarity)).toBeCloseTo(1, 5)
    })
  })
})
